name = "landing-pago"
compatibility_date = "2026-06-15"
preview_urls = false
workers_dev = true

[vars]
MP_FORCE_SANDBOX = "true"

[[d1_databases]]
binding = "DB"
database_name = "c_order_adempiere"
database_id = "68f6eeac-7fbc-4b81-a5ab-da61c2604343"
remote = true
